version = 1

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/VishwasSomasekhariah/website"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]